apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
  labels:
    app: identityservice
spec:
  selector:
    matchLabels:
      app: identityservice
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      serviceAccountName: identityservice
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {import from cicd}
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            memory: "180Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        
          
        
        